
spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mariadb://localhost:3306/KAKAOPAY
    username: service
    password: service!@#$
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
